### ISSUE TITLE
README should mention how to integrate Slitter with existing project.

### ISSUE THREAD

**Issue by vi** [backtrace-labs/slitter-wip#13]
How does one use Slitter? Can one simply connect it to a project like Jemalloc? If not, can there be some example project showing Slitter's strenglths (maybe with a separate deliberately buggy example that demonstrates that Slitter crashes controllably more often compared to other allocactors)?

**Comment by pkhuong** [comment]
Hopefully https://github.com/backtrace-labs/slitter/blob/main/examples/demo.c is enough to get started and give you a taste.
